app:
  name: Employee Management Application
  version: v1
  description: ""

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/learning
    username: postgres
    password: senha
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
