app:
  name: Employee Management Application
  version: v1
  description: "API REST Employee management"

spring:
  datasource:
    url: jdbc:postgresql://ep-gentle-water-a2t57isi.eu-central-1.pg.koyeb.app:5432/koyebdb
    username: koyeb-adm
    password: npg_AWtYzVCnk21w
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
