app:
  name: Employee Management Application
  version: v1
  description: ""

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/learning
    username: root
    password: root123
  jpa:
    hibernate:
      ddl-auto: update
