app:
  name: Employee Management Application
  version: v1
  description: "API REST Employee management"

spring:
  datasource:
    url: jdbc:postgresql://yamanote.proxy.rlwy.net:24827/railway
    username: postgres
    password: tNWnwDFxZHNXylqTAkfSkxshudgYJmGa
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
