FROM maven:3.9.8-amazoncorretto-11-al2023 as build
RUN mkdir -p usr/src/app
WORKDIR /usr/src/app

ADD . /usr/src/app

RUN mvn package

FROM eclipse-temurin:21-jdk
RUN mkdir -p usr/src/app
WORKDIR /usr/src/app

COPY --from=build /api/target/api-0.0.1-SNAPSHOT.jar app.jar
CMD ["java","-jar","app.jar"]